# Generated by Django 5.0 on 2024-03-28 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.CharField(blank=True, choices=[(1, 'Baixa Visão'), (2, 'Cegueira'), (3, 'Visão Monocular'), (4, 'Deficiência Auditiva'), (5, 'Deficiência Física'), (6, 'deficiência intelectual'), (7, 'Surdez'), (8, 'Surdocegueira'), (9, 'Transtorno do Espectro Autista (TEA)'), (10, 'Altas Habilidades ou Superdotação')], max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(blank=True, choices=[(1, 'Ensino Fundamental Anos Iniciais'), (2, 'Ensino Fundamental Anos Finais'), (3, 'Ensino Medio')], max_length=300, null=True)),
                ('serie', models.CharField(blank=True, choices=[(1, '1 Ano'), (2, '2 Ano'), (3, '3 Ano'), (4, '4 Ano'), (5, '5 Ano'), (6, '6 Ano'), (7, '7 Ano'), (8, '8 Ano'), (9, '9 Ano'), (10, '1 Série'), (11, '2 Série'), (12, '3 Série')], max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(blank=True, choices=[(1, 'Administrador Master'), (2, 'Administrador'), (3, 'Professor'), (4, 'Estudante'), (5, 'Saúde')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Escola')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('localizacao', models.CharField(choices=[(1, 'Rural'), (2, 'Urbana')], max_length=300)),
                ('dep_adm', models.CharField(choices=[(1, 'Municiapal'), (2, 'Estadual')], max_length=300)),
                ('codigo_inep', models.CharField(max_length=300)),
                ('etapa', models.ManyToManyField(blank=True, null=True, related_name='escola_etapas', to='core.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('estrategia', models.TextField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_competencia', to='core.competencia')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_habilidade', to='core.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('escola', models.ManyToManyField(related_name='integrante_escolas', to='core.escola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrante_user', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integrante_perfil', to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('dificiencia', models.ManyToManyField(blank=True, null=True, related_name='estudante_deficiencias', to='core.deficiencia')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estudante_escola', to='core.escola')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estudante_etapa', to='core.etapa')),
                ('integrante', models.ManyToManyField(blank=True, null=True, related_name='estudante_integrantes', to='core.integrante')),
            ],
        ),
        migrations.CreateModel(
            name='Pdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('concluido', models.BooleanField(default=False)),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdi_arquivo', to='core.arquivo')),
                ('competencia', models.ManyToManyField(blank=True, null=True, related_name='pdi_competencias', to='core.competencia')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdi_estudante', to='core.estudante')),
                ('habilidade', models.ManyToManyField(blank=True, null=True, related_name='pdi_habilidades', to='core.habilidade')),
                ('integrante', models.ManyToManyField(to='core.integrante')),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='pdi',
            field=models.ManyToManyField(blank=True, null=True, related_name='estudante_pdis', to='core.pdi'),
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.TextField()),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicacao_arquivo', to='core.arquivo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integrante')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacao_pdi', to='core.pdi')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_arquivo', to='core.arquivo')),
                ('formulario', models.ManyToManyField(related_name='avaliacao_formularios', to='core.formulario')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_pdi', to='core.pdi')),
            ],
        ),
    ]
