# Generated by Django 5.0 on 2023-12-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integrante')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pdi')),
            ],
        ),
    ]
