# Generated by Django 5.0 on 2024-03-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_competencia_competencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='nome',
        ),
    ]
