# Generated by Django 5.0 on 2024-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='codigo_inep',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='dep_adm',
            field=models.CharField(default='teste', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='etapas',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='localizacao',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
