# Generated by Django 5.0 on 2024-04-13 18:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pdi_habilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_arquivo', to='core.arquivo'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comunicacao_arquivo', to='core.arquivo'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='menssagem',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estrategia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pdi_arquivo', to='core.arquivo'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
