# Generated by Django 5.0 on 2024-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_avaliacao_arquivo_alter_comunicacao_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacao',
            name='menssagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estrategia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='descricao',
            field=models.TextField(),
        ),
    ]
